In [2]:
import numpy as np

In [3]:
#Array intialization
a=np.array([1,2,3,4])
b=np.empty(5,dtype=np.float32)
c=np.zeros(5)
d=np.ones((3,3),dtype=np.int32)
e=np.eye(5)
f=np.zeros_like(a)
g=np.linspace(0.,10.,5)
h=np.arange(0,10,2)
i=np.logspace(-5,2,10)
j=np.copy(a)

In [4]:
for i in [a,b,c,d,e,f,g,h,i,j]:
    print(i)

[1 2 3 4]
[4.2056068e+07 3.3875921e-12 2.3653862e+20 1.8939477e+34 4.6280042e+27]
[0. 0. 0. 0. 0.]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[0 0 0 0]
[ 0.   2.5  5.   7.5 10. ]
[0 2 4 6 8]
[1.00000000e-05 5.99484250e-05 3.59381366e-04 2.15443469e-03
 1.29154967e-02 7.74263683e-02 4.64158883e-01 2.78255940e+00
 1.66810054e+01 1.00000000e+02]
[1 2 3 4]


In [6]:
#Indexing
a=np.arange(10)
a[:3]=0
print(a)
a[2:5]=1
print(a)
a[:-3]=2
print(a)
#a[None,:]
print(a[None,:])
print(a[[1,1,3,8]],'\n')
a=a.reshape(2,5)
print(a,'\n')
print(a.T,'\n')
#b=np.transpose(a,(5,2))
#print(b)
print([a<3])

[0 0 0 3 4 5 6 7 8 9]
[0 0 1 1 1 5 6 7 8 9]
[2 2 2 2 2 2 2 7 8 9]
[[2 2 2 2 2 2 2 7 8 9]]
[2 2 2 8] 

[[2 2 2 2 2]
 [2 2 7 8 9]] 

[[2 2]
 [2 2]
 [2 7]
 [2 8]
 [2 9]] 

[array([[ True,  True,  True,  True,  True],
       [ True,  True, False, False, False]])]


# Array properties

In [7]:
a.shape

(2, 5)

In [8]:
len(a)

2

In [9]:
a.ndim

2

In [10]:
a.sort(axis=1)

In [11]:
a.flatten()

array([2, 2, 2, 2, 2, 2, 2, 7, 8, 9])

In [12]:
a.conj()

array([[2, 2, 2, 2, 2],
       [2, 2, 7, 8, 9]])

In [13]:
a.astype(np.int16)

array([[2, 2, 2, 2, 2],
       [2, 2, 7, 8, 9]], dtype=int16)

In [14]:
a.tolist()

[[2, 2, 2, 2, 2], [2, 2, 7, 8, 9]]

In [15]:
np.argmax(a,axis=1)

array([0, 4], dtype=int64)

In [16]:
np.argmax(a,axis=0)

array([0, 0, 1, 1, 1], dtype=int64)

In [17]:
np.cumsum(a)

array([ 2,  4,  6,  8, 10, 12, 14, 21, 29, 38], dtype=int32)

In [18]:
np.any(a)

True

In [19]:
np.all(a)

True

In [20]:
np.argsort(a,axis=1)

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]], dtype=int64)

In [21]:
np.where(a<5)

(array([0, 0, 0, 0, 0, 1, 1], dtype=int64),
 array([0, 1, 2, 3, 4, 0, 1], dtype=int64))

In [22]:
np.exp(a)

array([[7.38905610e+00, 7.38905610e+00, 7.38905610e+00, 7.38905610e+00,
        7.38905610e+00],
       [7.38905610e+00, 7.38905610e+00, 1.09663316e+03, 2.98095799e+03,
        8.10308393e+03]])

In [23]:
np.power(a,2)

array([[ 4,  4,  4,  4,  4],
       [ 4,  4, 49, 64, 81]], dtype=int32)

In [24]:
np.sin(a)

array([[0.90929743, 0.90929743, 0.90929743, 0.90929743, 0.90929743],
       [0.90929743, 0.90929743, 0.6569866 , 0.98935825, 0.41211849]])

In [25]:
np.radians(a)

array([[0.03490659, 0.03490659, 0.03490659, 0.03490659, 0.03490659],
       [0.03490659, 0.03490659, 0.12217305, 0.13962634, 0.15707963]])

In [26]:
np.degrees(a)

array([[114.59155903, 114.59155903, 114.59155903, 114.59155903,
        114.59155903],
       [114.59155903, 114.59155903, 401.07045659, 458.3662361 ,
        515.66201562]])

In [27]:
np.var(a)

7.760000000000001

In [28]:
np.std(a,axis=1)

array([0.        , 3.00665928])

In [29]:
np.dot(a,b)

array([3.78789640e+34, 1.51515861e+35])

In [30]:
np.sum(a,axis=1)
#row wise

array([10, 28])

In [31]:
np.sum(a,axis=0)
#column wise

array([ 4,  4,  9, 10, 11])

In [32]:
a

array([[2, 2, 2, 2, 2],
       [2, 2, 7, 8, 9]])

In [33]:
np.abs(a)

array([[2, 2, 2, 2, 2],
       [2, 2, 7, 8, 9]])

In [34]:
a=np.arange(9)
a=a.reshape(3,3)
eigen_a=np.linalg.eig(a)

In [35]:
print(eigen_a)

(array([ 1.33484692e+01, -1.34846923e+00, -2.48477279e-16]), array([[ 0.16476382,  0.79969966,  0.40824829],
       [ 0.50577448,  0.10420579, -0.81649658],
       [ 0.84678513, -0.59128809,  0.40824829]]))


In [36]:
np.fft.fft(a)

array([[ 3. +0.j       , -1.5+0.8660254j, -1.5-0.8660254j],
       [12. +0.j       , -1.5+0.8660254j, -1.5-0.8660254j],
       [21. +0.j       , -1.5+0.8660254j, -1.5-0.8660254j]])

In [37]:
f=np.fft.fftfreq(len(a))
print(f)

[ 0.          0.33333333 -0.33333333]


In [38]:
np.fft.fftshift(f)

array([-0.33333333,  0.        ,  0.33333333])

In [39]:
np.fft.rfft(a)

array([[ 3. +0.j       , -1.5+0.8660254j],
       [12. +0.j       , -1.5+0.8660254j],
       [21. +0.j       , -1.5+0.8660254j]])

In [40]:
np.fft.rfftfreq(len(a))

array([0.        , 0.33333333])

In [41]:
np.ceil(a)

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [42]:
np.ceil(5.01)

6.0

In [43]:
np.floor(5.9999)

5.0

In [44]:
np.round(5.5)

6.0

In [45]:
np.round(5.49)

5.0

In [46]:
from numpy.random import normal, seed, rand, uniform, randint

In [47]:
normal(loc=0,scale=1,size=10)

array([-0.68773957,  0.62073162,  0.15100515,  0.71062034, -0.37440613,
       -0.34683116,  0.69515662, -0.56752922,  0.84110986,  0.42006751])

In [48]:
seed(1997)
rand(20)

array([0.77114815, 0.07475717, 0.52631002, 0.97508762, 0.99222565,
       0.46513466, 0.61113455, 0.5694625 , 0.66771925, 0.78678006,
       0.87523831, 0.39976015, 0.97275062, 0.21807146, 0.06672001,
       0.57663487, 0.5596097 , 0.56464953, 0.41424667, 0.47924166])

In [49]:
uniform(1,30,20)

array([11.55434045, 13.49718312, 14.90446388, 16.37943401, 10.44148809,
       27.46281573, 25.456403  , 15.9349544 , 23.83058135, 21.43020505,
       14.95901158,  7.38271294, 19.25730707,  1.09310549, 24.26407333,
       17.95594754, 19.37965318, 16.87167096,  5.65245032, 12.70687933])

In [50]:
randint(1,16,20)

array([ 6,  1,  3,  7,  6, 10, 12,  6,  3, 10, 15,  6,  8, 12,  2,  2,  5,
       10, 12, 14])

another book
# Numpy full

In [51]:
import numpy as np
a=np.array([0,1,2,3])
a

array([0, 1, 2, 3])

In [52]:
a.ndim

1

In [53]:
a.shape

(4,)

In [55]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
b=np.arange(1,9,2)
b

array([1, 3, 5, 7])

In [ ]:
c=np.linspace()