In [12]:
import random
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import copy

In [13]:
def generate_random_numbers(min_val, max_val, total_sum, num_elements):
    if total_sum < num_elements * min_val or total_sum > num_elements * max_val:
        raise ValueError("No valid solution exists with the given parameters.")

    remaining_sum = total_sum - num_elements * min_val
    random_numbers = [min_val] * num_elements
    for i in range(remaining_sum):
        idx = random.randint(0, num_elements - 1)
        if random_numbers[idx] < max_val:
            random_numbers[idx] += 1

    return random_numbers

In [14]:
lst_pq=[100,200,250,300,500]
min_k=50
max_k=250

In [19]:
# balance_left=0
pq_k=[]
pq_l=[]
for j in range(len(lst_pq)):
    total_sum=lst_pq[j]
    temp=generate_random_numbers(min_k, max_k, total_sum, 2)
    for k in temp:
        pq_k.append(k)
    for l in range(len(temp)):
        total_sum=temp[l]
        min_l=round(min(temp)/4)
        max_l=round(max(temp)/2)
        temp1=generate_random_numbers(min_l, max_l, total_sum, 3)
        for ll in temp1:
            pq_l.append(ll)

print(pq_k)
print(pq_l)

[50, 50, 101, 99, 125, 125, 142, 158, 230, 250]
[17, 18, 15, 17, 15, 18, 35, 32, 34, 34, 29, 36, 41, 41, 43, 45, 42, 38, 49, 47, 46, 56, 45, 57, 85, 75, 70, 81, 88, 81]


In [38]:
J=5
K=10
L=30
M=5

In [46]:
pq_jk=np.zeros((J,K),dtype=np.int32)
pq_kl=np.zeros((K,L),dtype=np.int32)
pq_lm=np.zeros((L,M),dtype=np.int32)

In [47]:
print(pq_kl)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]


In [48]:
a=0
for i in range(len(pq_k)):
    for j in range(i*3,(i*3)+3):
        pq_kl[i][j]=pq_l[a]
        a+=1
print(pq_kl)

[[17 18 15  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0]
 [ 0  0  0 17 15 18  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0]
 [ 0  0  0  0  0  0 35 32 34  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0 34 29 36  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 41 41 43  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 45 42 38  0  0  0  0  0  0
   0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 49 47 46  0  0  0
   0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 56 45 57
   0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  85 75 70  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0 81 88 81]]
